### ISSUE TITLE
When I run scence.py, RPly: Unable to open file [Open3D WARNING] Read PLY failed: unable to open file: /data/COINS/configuration/PROX/scenes_semantics/BasementSittingBooth_semantic.ply

### ISSUE THREAD

**Issue by jyhflash** [zkf1997/COINS#10]
create scene: BasementSittingBooth
RPly: Unable to open file
[Open3D WARNING] Read PLY failed: unable to open file: /data/COINS/configuration/PROX/scenes_semantics/BasementSittingBooth_semantic.ply
unable to convert colors!
Traceback (most recent call last):
  File "scene.py", line 501, in <module>
    scenes[scene_name] = Scene(scene_name=scene_name)
  File "scene.py", line 198, in __init__
    semantic_mesh = to_trimesh(o3d.io.read_triangle_mesh(scene_semantic_path))
  File "scene.py", line 40, in to_trimesh
    vertex_normals=np.asarray(o3d_mesh.vertex_normals), process=False
  File "/opt/conda/envs/COINS/lib/python3.7/site-packages/trimesh/base.py", line 167, in __init__
    self.vertex_normals = vertex_normals
  File "/opt/conda/envs/COINS/lib/python3.7/site-packages/trimesh/base.py", line 506, in vertex_normals
    if np.ptp(values) < tol.merge:
  File "<__array_function__ internals>", line 6, in ptp
  File "/opt/conda/envs/COINS/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2630, in ptp
    return _methods._ptp(a, axis=axis, out=out, **kwargs)
  File "/opt/conda/envs/COINS/lib/python3.7/site-packages/numpy/core/_methods.py", line 276, in _ptp
    umr_maximum(a, axis, None, out, keepdims),
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by jyhflash** [comment]
fix
