### ISSUE TITLE
When I run :python two_stage_sample.py --exp_name test --lr_posa 0.01 --max_step_body 100  --weight_penetration 100 --weight_pose 10 --weight_init 0.01  --weight_contact_semantic 1 --num_sample 8 --num_try 1  --visualize 1 --full_scene 1 --interaction 'sit on-chair' --scene_name 'MPH16'

### ISSUE THREAD

**Issue by jyhflash** [zkf1997/COINS#11]
Traceback (most recent call last):
  File "two_stage_sample.py", line 11, in <module>
    from transform_trainer import *
  File "/data/COINS/interaction/transform_trainer.py", line 21, in <module>
    from pytorch_lightning.profiler import SimpleProfiler, AdvancedProfiler
ImportError: cannot import name 'SimpleProfiler' from 'pytorch_lightning.profiler' (/opt/conda/envs/COINS/lib/python3.7/site-packages/pytorch_lightning/profiler/__init__.py)

**Comment by jyhflash** [comment]
fix
