### ISSUE TITLE
run python scene.py but some errors happened

### ISSUE THREAD

**Issue by jyhflash** [zkf1997/COINS#9]
create scene: BasementSittingBooth
Traceback (most recent call last):
  File "/data/COINS/data/scene.py", line 502, in <module>
    scenes[scene_name] = Scene(scene_name=scene_name)
  File "/data/COINS/data/scene.py", line 208, in __init__
    self.get_object_nodes(vertex_category_ids, vertex_instance_ids, segment_mesh)
  File "/data/COINS/data/scene.py", line 268, in get_object_nodes
    face_ids = np.nonzero((vertex_instance_ids[segment_mesh.faces] == instance_id).sum(axis=1) == 3)[0]
IndexError: index 368517 is out of bounds for axis 0 with size 368517
(base) root@7e0323b1f33e:/data/COINS/data# python scene.py
create scene: BasementSittingBooth
(368517,) (731533, 3) 1
Traceback (most recent call last):
  File "/data/COINS/data/scene.py", line 502, in <module>
    scenes[scene_name] = Scene(scene_name=scene_name)
  File "/data/COINS/data/scene.py", line 208, in __init__
    self.get_object_nodes(vertex_category_ids, vertex_instance_ids, segment_mesh)
  File "/data/COINS/data/scene.py", line 268, in get_object_nodes
    face_ids = np.nonzero((vertex_instance_ids[segment_mesh.faces] == instance_id).sum(axis=1) == 3)[0]
IndexError: index 368517 is out of bounds for axis 0 with size 368517

**Comment by jyhflash** [comment]
fix
